[[Shaderc]]
arch = "aarch64"
git-tree-sha1 = "995e8190cae23e2c65f354979e1116b070215de3"
os = "macos"

    [[Shaderc.download]]
    sha256 = "110428e19b9ef408aa3a374c26c66516276aeb6a91d44b25420702ac64f5472f"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.aarch64-apple-darwin.tar.gz"
[[Shaderc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e41badcc5df3eac46af68950a09db35e5ae3ddb5"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "f2da5f1893bff6fc689d8e594a5cd6bb03e74d7d39c082bae48fd314e6c4ae16"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Shaderc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0d721634734fc5342e9693f36e05d8b4207da62"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "f6ed5b9e0e490063453a3d78dcb66ae3818a1e67e51875ff2b24b05ec26faaa6"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Shaderc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5aff1bcaa77ec50b67c6984720305b09fbd1b9ac"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "fdde75c448b705d8672792e7f90c3b7e6e1c89af0bfa06c14f0a8ad43dc514c3"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[Shaderc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8eeffcbdd1df013b6a12a0a50e73c9107cbe34a5"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "bb58c07aebf61fc2f2681f7220fd2204fd10ca95315e1d947766479ef63ca4a2"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[Shaderc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "561e97bdd736d7e73ebed2b6c428e9d5827284ab"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "dd8a356173d9047cf2f69231b187bfea550aad01f84d66af0056c6d1e2237d11"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Shaderc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee6384023666ed09f39a082b442b59274ce9a588"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "706b9cff9a2c93f95373d6729fea083a2e62ad2e7f6c315b5a471048130cbd1c"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Shaderc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e213ee6d1291b719a3f47e602b493075e6693012"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "5aadaa3541110c6e4482b31eca8f9a48371af778333430fe26e05df61b46f294"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Shaderc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c93013fa069fc167ac4a543633706f510fdf4fcb"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "a1d6b3a220a8667b132a7ebb7aa5f4f6e06acefeeab14c9d475e129ea131ac39"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Shaderc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25f6e2467d444184f258ae6bc557e9acd15c1e9a"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "f38e274df2d1015796484e175cb31d425de4a34319f946cfea37a6ee0a4641ff"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Shaderc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cc1c85d28f9fb776b894e975c80ff99cf74f8d0"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "a19138c5e47e12a5ea775675e26631a287f150a46454e9bc274421dd31d188de"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Shaderc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea2ff74d72f4c173f9c51cc61daa7123d8dd92c4"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "b1b9895491f42154abcdac565d5cb6b2ccfab72cbac922d31e506bf3b8596736"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Shaderc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e907e1ac39276a29a87c27c60b777aaf234cbc0"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "9584bc504f0a56f438646abf5bdb70574e766146b71efda7a58f9e485fc32c99"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Shaderc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb00630f391ac692333e32bdf95df2e4b48631f0"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "cff8d678b1853a8df2dab056de38d25ea5bdac4aa381bf1dd23fa7b742fd71fc"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.i686-linux-gnu-cxx03.tar.gz"
[[Shaderc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "792a17622a0d87674e896930cf25bbb01349019b"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "a284ae08ed1419577f50605a1e0a7abccd931b6462b0a124d94cb7a103fad3b7"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Shaderc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f23f65d19ab0173ea8f354cdc68d693cf720f2c"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "407f0d7f25507a69a5174c5c8b9b4d2fa795301a6acf6fd78c4b29e2b7486325"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.i686-linux-musl-cxx03.tar.gz"
[[Shaderc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c66b31e488441d4aa7188f2e5658b0de735209d8"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "20d84361a5c195f01aadaa8310e29e3b65cbe89a1ae61d12d6a171868d1657e5"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.i686-linux-musl-cxx11.tar.gz"
[[Shaderc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1b992e94f5eb80a4403cc017baa3cad0f3d5ebe"
os = "windows"

    [[Shaderc.download]]
    sha256 = "d3d0e295a42a468d0706ea9f2c2e2296e6ae636a8b0510144b148f88780d51e5"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[Shaderc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "865fd18e65b0ad2c832d3f94696f3b9236ac990b"
os = "windows"

    [[Shaderc.download]]
    sha256 = "539c4caeeb3a77957c3f55b7db3ee6792cb90289f8c622eaf0ee41573f7c0a55"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[Shaderc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbf0892de843c29375860167117bfac0ac3520e9"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "655dca8e8fc96e92837b89cf013acc43077fe251b76f012ae939d1cb2920e62a"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Shaderc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b59baa63b687871bf3dd8b34626e8c12b84fe05e"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "f3db821abfdb379f3469431fcb3afa59950338a084614b6de5fbf434f1b7f441"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Shaderc]]
arch = "x86_64"
git-tree-sha1 = "b10839bb830d4b27b1af39e37774f908053cf3d8"
os = "macos"

    [[Shaderc.download]]
    sha256 = "6899ea6a63fdee0e3cb57d6d19a8b7023a44dc0c66f310a1962ed4fc07497f7e"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-apple-darwin.tar.gz"
[[Shaderc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42f3f18101e95992390e9c817657b91d8d80e4fc"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "bb170ed8c2b52d41ace0e90a91f4a72bb1c1ba04a72171fdc98039fc71f353ee"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Shaderc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef3efe42db38cdc239332b508ac6383dd88e13c5"
libc = "glibc"
os = "linux"

    [[Shaderc.download]]
    sha256 = "7154ecf6508b9c21c4a7c295435c91f20ac0e3321645bb4f56bf1c7a86242bbc"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Shaderc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8946ed838097f424e1caad4d22d710a2089a5d0"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "a0726acb8e8291b68a54d5b661caf62981d4e3a1fc9b4b75a204c05789682253"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Shaderc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0fe586ca42967e74672f7fb1d93c8d1aaff98ea"
libc = "musl"
os = "linux"

    [[Shaderc.download]]
    sha256 = "e364b64c11471c1a6c54f4bbfb54a7e63b03a4d37e966896563f275fb1e63778"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[Shaderc]]
arch = "x86_64"
git-tree-sha1 = "dc2f6945d8c3030cd078fb9152ae81720593f264"
os = "freebsd"

    [[Shaderc.download]]
    sha256 = "ee8ea38659a6b74aba53bd9d91ff0c26730e7969b40d5c10d3c95a84bf7fa633"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-unknown-freebsd.tar.gz"
[[Shaderc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9caef2d82cd2e47adfba428c5283471e8984e98d"
os = "windows"

    [[Shaderc.download]]
    sha256 = "6522788a6d97060d8eaf842c1b1d33e5c087cb3a6bc52855d5ca605d20583a44"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Shaderc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f2fe3f04c15af62b8757f30dba2b07c9aa6c54e"
os = "windows"

    [[Shaderc.download]]
    sha256 = "a495d1265e0758f907720f08edd6076ec86e13c721e4e0886705fa75d0ec5bc0"
    url = "https://github.com/JuliaBinaryWrappers/Shaderc_jll.jl/releases/download/Shaderc-v2022.1.0+0/Shaderc.v2022.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
