# Autogenerated wrapper script for Shaderc_jll for x86_64-w64-mingw32-cxx11
export glslangValidator, glslc, libSPIRV_Tools_shared, libshaderc_shared, spirv_as, spirv_cfg, spirv_dis, spirv_link, spirv_lint, spirv_opt, spirv_reduce, spirv_remap, spirv_val

JLLWrappers.@generate_wrapper_header("Shaderc")
JLLWrappers.@declare_library_product(libSPIRV_Tools_shared, "libSPIRV-Tools-shared.dll")
JLLWrappers.@declare_library_product(libshaderc_shared, "libshaderc_shared.dll")
JLLWrappers.@declare_executable_product(glslangValidator)
JLLWrappers.@declare_executable_product(glslc)
JLLWrappers.@declare_executable_product(spirv_as)
JLLWrappers.@declare_executable_product(spirv_cfg)
JLLWrappers.@declare_executable_product(spirv_dis)
JLLWrappers.@declare_executable_product(spirv_link)
JLLWrappers.@declare_executable_product(spirv_lint)
JLLWrappers.@declare_executable_product(spirv_opt)
JLLWrappers.@declare_executable_product(spirv_reduce)
JLLWrappers.@declare_executable_product(spirv_remap)
JLLWrappers.@declare_executable_product(spirv_val)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libSPIRV_Tools_shared,
        "bin\\libSPIRV-Tools-shared.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libshaderc_shared,
        "bin\\libshaderc_shared.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        glslangValidator,
        "bin\\glslangValidator.exe",
    )

    JLLWrappers.@init_executable_product(
        glslc,
        "bin\\glslc.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_as,
        "bin\\spirv-as.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_cfg,
        "bin\\spirv-cfg.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_dis,
        "bin\\spirv-dis.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_link,
        "bin\\spirv-link.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_lint,
        "bin\\spirv-lint.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_opt,
        "bin\\spirv-opt.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_reduce,
        "bin\\spirv-reduce.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_remap,
        "bin\\spirv-remap.exe",
    )

    JLLWrappers.@init_executable_product(
        spirv_val,
        "bin\\spirv-val.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
